### ISSUE TITLE
Back to School Release Tracker

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/mosviz#72]
### Required
- [ ] installation via astroconda
- [ ] installation faq for glue (and pointer to this from MOSViz documentation)
- [ ] data loader for JWST NIRSpec MSA + NIRCam level 2 + 3 
- [ ] data loader for ACS & WFC3 grisms 
- [ ] data loader for NIRISS grism + direct images 
- [ ] data loader for NIRCam grism + direct images (7) wizard works with ground-based data sets in SDSS format 
- [ ] wizard works with MOSFIRE & VIMOS data 

### Optional
- [ ] wizard works with DESI data (they carry LSF around in spectra files; David Kirkby)
